///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SimpleTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("108f015a-72de-41b1-a121-5e8b0a707eab", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SimpleTestRepository repository.
        /// </summary>
        public static SimpleTestRepository repo = SimpleTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.edgewordstraining.co.uk/demo-site/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.edgewordstraining.co.uk/demo-site/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0' at 86;30.", repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0Info, new RecordItemIndex(1));
            repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0.Click("86;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cap{Return}' with focus on 'EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0'.", repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0Info, new RecordItemIndex(2));
            repo.EdgewordsShopECommerceDemoSiteFor.WoocommerceProductSearchField0.PressKeys("cap{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.AddToCart' at 62;34.", repo.EdgewordsShopECommerceDemoSiteFor.AddToCartInfo, new RecordItemIndex(3));
            repo.EdgewordsShopECommerceDemoSiteFor.AddToCart.Click("62;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.ViewCart' at 73;19.", repo.EdgewordsShopECommerceDemoSiteFor.ViewCartInfo, new RecordItemIndex(4));
            repo.EdgewordsShopECommerceDemoSiteFor.ViewCart.Click("73;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.SomeATag' at 22;22.", repo.EdgewordsShopECommerceDemoSiteFor.SomeATagInfo, new RecordItemIndex(5));
            repo.EdgewordsShopECommerceDemoSiteFor.SomeATag.Click("22;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.ATagReturnToShop' at 102;37.", repo.EdgewordsShopECommerceDemoSiteFor.ATagReturnToShopInfo, new RecordItemIndex(6));
            repo.EdgewordsShopECommerceDemoSiteFor.ATagReturnToShop.Click("102;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsShopECommerceDemoSiteFor.Home' at 48;53.", repo.EdgewordsShopECommerceDemoSiteFor.HomeInfo, new RecordItemIndex(7));
            repo.EdgewordsShopECommerceDemoSiteFor.Home.Click("48;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'EdgewordsShopECommerceDemoSiteFor'.", repo.EdgewordsShopECommerceDemoSiteFor.SelfInfo, new RecordItemIndex(8));
            Host.Current.CloseApplication(repo.EdgewordsShopECommerceDemoSiteFor.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
