///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SimpleTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SimpleTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("b103164c-aa54-4de9-9519-6c3b226abc52")]
    public partial class SimpleTestRepository : RepoGenBaseFolder
    {
        static SimpleTestRepository instance = new SimpleTestRepository();
        SimpleTestRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder _edgewordsshopecommercedemositefor;

        /// <summary>
        /// Gets the singleton class instance representing the SimpleTestRepository element repository.
        /// </summary>
        [RepositoryFolder("b103164c-aa54-4de9-9519-6c3b226abc52")]
        public static SimpleTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SimpleTestRepository() 
            : base("SimpleTestRepository", "/", null, 0, false, "b103164c-aa54-4de9-9519-6c3b226abc52", ".\\RepositoryImages\\SimpleTestRepositoryb103164c.rximgres")
        {
            _edgewordsshopecommercedemositefor = new SimpleTestRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b103164c-aa54-4de9-9519-6c3b226abc52")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EdgewordsShopECommerceDemoSiteFor folder.
        /// </summary>
        [RepositoryFolder("49e25fe6-714d-4ae8-9f52-23dbdaa54f23")]
        public virtual SimpleTestRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder EdgewordsShopECommerceDemoSiteFor
        {
            get { return _edgewordsshopecommercedemositefor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class SimpleTestRepositoryFolders
    {
        /// <summary>
        /// The EdgewordsShopECommerceDemoSiteForAppFolder folder.
        /// </summary>
        [RepositoryFolder("49e25fe6-714d-4ae8-9f52-23dbdaa54f23")]
        public partial class EdgewordsShopECommerceDemoSiteForAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _woocommerceproductsearchfield0Info;
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _viewcartInfo;
            RepoItemInfo _someatagInfo;
            RepoItemInfo _atagreturntoshopInfo;
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new EdgewordsShopECommerceDemoSiteFor  folder.
            /// </summary>
            public EdgewordsShopECommerceDemoSiteForAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgewordsShopECommerceDemoSiteFor", "/dom[@domain='www.edgewordstraining.co.uk']", parentFolder, 30000, null, false, "49e25fe6-714d-4ae8-9f52-23dbdaa54f23", "")
            {
                _woocommerceproductsearchfield0Info = new RepoItemInfo(this, "WoocommerceProductSearchField0", ".//input[#'woocommerce-product-search-field-0']", 30000, null, "d1d968b3-5707-43d7-8c04-417e6621b28a");
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", ".//div[#'product-29']/?/?/form[@action='https://www.edgewordstraining.co.uk/demo-site/product/cap/']/button[@innertext='Add to cart']", 30000, null, "9e9057fc-3f7c-41c9-a72a-1396a03a176c");
                _viewcartInfo = new RepoItemInfo(this, "ViewCart", ".//div[#'content']//div[@innertext~'^\\ “Cap”\\ has\\ been\\ added\\ to\\ ']/a[@innertext='View cart']", 30000, null, "fdde1874-ce36-4178-ae9a-cd44999ae1e2");
                _someatagInfo = new RepoItemInfo(this, "SomeATag", ".//article[#'post-5']//form[@action='https://www.edgewordstraining.co.uk/demo-site/cart/']/table/tbody/tr[1]/td[1]/a[@innertext='×']", 30000, null, "55220de4-0ba5-4086-9d9d-01e5c199cec4");
                _atagreturntoshopInfo = new RepoItemInfo(this, "ATagReturnToShop", ".//article[#'post-5']/div//a[@innertext='Return to shop']", 30000, null, "9239df16-5f58-48b2-8360-636a9e131d0a");
                _homeInfo = new RepoItemInfo(this, "Home", ".//li[#'menu-item-42']/a[@innertext='Home']", 30000, null, "bc2f828f-b692-4d21-802e-3c7f6f167c74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49e25fe6-714d-4ae8-9f52-23dbdaa54f23")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49e25fe6-714d-4ae8-9f52-23dbdaa54f23")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WoocommerceProductSearchField0 item.
            /// </summary>
            [RepositoryItem("d1d968b3-5707-43d7-8c04-417e6621b28a")]
            public virtual Ranorex.InputTag WoocommerceProductSearchField0
            {
                get
                {
                    return _woocommerceproductsearchfield0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The WoocommerceProductSearchField0 item info.
            /// </summary>
            [RepositoryItemInfo("d1d968b3-5707-43d7-8c04-417e6621b28a")]
            public virtual RepoItemInfo WoocommerceProductSearchField0Info
            {
                get
                {
                    return _woocommerceproductsearchfield0Info;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("9e9057fc-3f7c-41c9-a72a-1396a03a176c")]
            public virtual Ranorex.ButtonTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("9e9057fc-3f7c-41c9-a72a-1396a03a176c")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The ViewCart item.
            /// </summary>
            [RepositoryItem("fdde1874-ce36-4178-ae9a-cd44999ae1e2")]
            public virtual Ranorex.ATag ViewCart
            {
                get
                {
                    return _viewcartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ViewCart item info.
            /// </summary>
            [RepositoryItemInfo("fdde1874-ce36-4178-ae9a-cd44999ae1e2")]
            public virtual RepoItemInfo ViewCartInfo
            {
                get
                {
                    return _viewcartInfo;
                }
            }

            /// <summary>
            /// The SomeATag item.
            /// </summary>
            [RepositoryItem("55220de4-0ba5-4086-9d9d-01e5c199cec4")]
            public virtual Ranorex.ATag SomeATag
            {
                get
                {
                    return _someatagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SomeATag item info.
            /// </summary>
            [RepositoryItemInfo("55220de4-0ba5-4086-9d9d-01e5c199cec4")]
            public virtual RepoItemInfo SomeATagInfo
            {
                get
                {
                    return _someatagInfo;
                }
            }

            /// <summary>
            /// The ATagReturnToShop item.
            /// </summary>
            [RepositoryItem("9239df16-5f58-48b2-8360-636a9e131d0a")]
            public virtual Ranorex.ATag ATagReturnToShop
            {
                get
                {
                    return _atagreturntoshopInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagReturnToShop item info.
            /// </summary>
            [RepositoryItemInfo("9239df16-5f58-48b2-8360-636a9e131d0a")]
            public virtual RepoItemInfo ATagReturnToShopInfo
            {
                get
                {
                    return _atagreturntoshopInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("bc2f828f-b692-4d21-802e-3c7f6f167c74")]
            public virtual Ranorex.ATag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("bc2f828f-b692-4d21-802e-3c7f6f167c74")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}